name: workflow

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: build
        run: ls && yarn run docs:build

