name: workflow

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: yarn install
      - name: Build docs
        run: ls && yarn run docs:build

