name: vuepress

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: install
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
        run: yarn install
      - name: build
        run: yarn run docs:build

