name: workflow

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: init
        uses: actions/setup-node
        with:
          node-version: 12.x
      - name: install
        run: yarn install
      - name: build
        run: yarn run docs:build

